version: '3.7'
services:
  api:
    container_name: api-drivers
    build:
      context: .
      dockerfile: "./dockerfile"
    ports:
      - "8080:80"
    depends_on:
      - db_drivers
    networks:
      - application
  db_drivers:
      image: "mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04"
      container_name: db_drivers
      environment:
        SA_PASSWORD: "Pass123!"
        ACCEPT_EULA: "Y"
      restart: always   
      ports:
        - "1433:1433" 
      networks:
      - application

networks:
  application:
    driver: bridge